export'package:flutter_application_1/screens/lista_proveedores.dart';
export 'package:flutter_application_1/screens/edit_product_screen.dart';
export 'package:flutter_application_1/screens/lista_categorias.dart';
export 'package:flutter_application_1/screens/error_screen.dart';
export 'package:flutter_application_1/screens/registro_screen.dart';
export 'package:flutter_application_1/screens/login_screen.dart';
export 'package:flutter_application_1/screens/lista_productos_screen.dart';
export 'package:flutter_application_1/screens/carro_screen.dart';
export 'package:flutter_application_1/screens/loading_screen.dart';
export 'package:flutter_application_1/screens/detalle_producto_screen.dart';